version: '3'

services:
  nodejs:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    networks:
      - my_network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my_network

networks:
  my_network:
