version: '3.8'

services:

  api-gateway:
      build:
        context: ./api-gateway
      ports:
        - "80:80"
      depends_on:
        - user-microservice
        - leaderboard-microservice
        - notification-microservice
        - quiz-microservice

  user-microservice:
    build:
      context: ./user-authentication-microservice
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/my_database
      SPRING_DATASOURCE_USERNAME: new
      SPRING_DATASOURCE_PASSWORD: password

  leaderboard-microservice:
    build:
      context: ./leaderboard-microservice
    ports:
      - "3005:3005"
    volumes:
      - ./leaderboard-microservice:/usr/src/app

  notification-microservice:
    build:
      context: ./notification-microservice
    ports:
      - "3008:3008"
    volumes:
      - ./notification-microservice:/app
    depends_on:
      rabbitmq:
        condition: service_healthy

  quiz-microservice:
    build:
      context: ./quiz-microservice
    ports:
      - "3000:3000"
    volumes:
      - ./quiz-microservice:/usr/src/app

  rabbitmq:
    image: rabbitmq:3.8
    ports:
      - "5672:5672"
    healthcheck:
      test: "exit 0"

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    healthcheck:
      test: "exit 0"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: my_database 
      MYSQL_USER: new 
      MYSQL_PASSWORD: password
    volumes:
      - ./User-sql:/docker-entrypoint-initdb.d

volumes:
  mysql-data: