version: '3.8'

services:
  spring-app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/my_database
      SPRING_DATASOURCE_USERNAME: new
      SPRING_DATASOURCE_PASSWORD: password

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    healthcheck:
      test: "exit 0"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: my_database 
      MYSQL_USER: new 
      MYSQL_PASSWORD: password
    volumes:
      - ./User-sql:/docker-entrypoint-initdb.d

volumes:
  mysql-data: